version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - automd
  - bumpp
  - eslintcache
  - importantimport
  - masknet
  - modelcontextprotocol
  - moeru
  - pkgroll
  - sonarjs
  - streamable
  - valibot
  - vercel
  - whatwg
  - xsai
  - xsmcp
  - xsrpc
  - xsschema
ignoreWords: []
import: []
