version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - automd
  - bumpp
  - eslintcache
  - importantimport
  - masknet
  - modelcontextprotocol
  - moeru
  - pkgroll
  - sonarjs
  - vercel
  - xsai
  - xsmcp
ignoreWords: []
import: []
