name: gh-pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    uses: importantimport/.github/.github/workflows/pnpm-gh-pages-artifact.yml@main
    with:
      build: pnpm -r build
      path: docs/dist
